fix the bugs when the streams features open, Url not declared
Maxuss/chatgpt_rs pull request #12
Opened 2023-04-04 08:08 UTC by einsli

This pr fixes the following problem. When the streams feature of chatgpt_rs is enabled, the following error is reported ”Url not declared“！

2023-04-04 12:04 UTC, Maxuss requested changes
Thank you for pointing out these things I missed last update! Just a few changes and it's good to go.

2023-04-04 12:04 UTC, Maxuss commented on src/client.rs
>              )
This can be changed to:
```suggestion
            .post(self.config.api_url.clone())
```

2023-04-04 12:04 UTC, Maxuss commented on src/client.rs
>              )
This as well

2023-04-10 11:34 UTC, tmac33 approved these changes
Nice one!

2023-04-15 07:41 UTC, merged